In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7645, 4553, 7470, 724],
 [7645, 4553, 7470, 3395],
 [7645, 3683, 7470, 7229],
 [4998, 13, 338, 6713, 5230],
 [4998, 13, 338, 6713, 9158],
 [247, 7645, 9871, 7470, 5678],
 [9186, 3654, 3377, 6713]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7645 4553 7470  724]
 [   0    0    0    0 7645 4553 7470 3395]
 [   0    0    0    0 7645 3683 7470 7229]
 [   0    0    0 4998   13  338 6713 5230]
 [   0    0    0 4998   13  338 6713 9158]
 [   0    0    0  247 7645 9871 7470 5678]
 [   0    0    0    0 9186 3654 3377 6713]]


In [9]:
## feature representation
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 289ms/step


array([[[-0.02139989,  0.02429349, -0.02829921,  0.00676638,
         -0.04962354,  0.02847579,  0.02221665, -0.04135281,
         -0.02005035,  0.04900945],
        [-0.02139989,  0.02429349, -0.02829921,  0.00676638,
         -0.04962354,  0.02847579,  0.02221665, -0.04135281,
         -0.02005035,  0.04900945],
        [-0.02139989,  0.02429349, -0.02829921,  0.00676638,
         -0.04962354,  0.02847579,  0.02221665, -0.04135281,
         -0.02005035,  0.04900945],
        [-0.02139989,  0.02429349, -0.02829921,  0.00676638,
         -0.04962354,  0.02847579,  0.02221665, -0.04135281,
         -0.02005035,  0.04900945],
        [ 0.00334171, -0.03187992, -0.04227031,  0.03772104,
         -0.04919243,  0.02148498, -0.04214923,  0.01312138,
          0.02923261, -0.04654753],
        [ 0.04151208,  0.04781184, -0.00894835,  0.00177987,
         -0.04709848, -0.02507459, -0.0444037 , -0.04201303,
          0.02035517,  0.03735104],
        [-0.00091701, -0.01042627,  0.01509664,  0.0

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 7645, 4553, 7470,  724])

In [14]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 54ms/step


array([[-0.02139989,  0.02429349, -0.02829921,  0.00676638, -0.04962354,
         0.02847579,  0.02221665, -0.04135281, -0.02005035,  0.04900945],
       [-0.02139989,  0.02429349, -0.02829921,  0.00676638, -0.04962354,
         0.02847579,  0.02221665, -0.04135281, -0.02005035,  0.04900945],
       [-0.02139989,  0.02429349, -0.02829921,  0.00676638, -0.04962354,
         0.02847579,  0.02221665, -0.04135281, -0.02005035,  0.04900945],
       [-0.02139989,  0.02429349, -0.02829921,  0.00676638, -0.04962354,
         0.02847579,  0.02221665, -0.04135281, -0.02005035,  0.04900945],
       [ 0.00334171, -0.03187992, -0.04227031,  0.03772104, -0.04919243,
         0.02148498, -0.04214923,  0.01312138,  0.02923261, -0.04654753],
       [ 0.04151208,  0.04781184, -0.00894835,  0.00177987, -0.04709848,
        -0.02507459, -0.0444037 , -0.04201303,  0.02035517,  0.03735104],
       [-0.00091701, -0.01042627,  0.01509664,  0.04689981, -0.03477221,
        -0.04916836, -0.02827436, -0.00496311