In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3711, 9743, 3417, 5090],
 [3711, 9743, 3417, 1813],
 [3711, 5837, 3417, 74],
 [1264, 920, 4563, 3551, 7379],
 [1264, 920, 4563, 3551, 1024],
 [2504, 3711, 2461, 3417, 8032],
 [5044, 9780, 8983, 3551]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3711 9743 3417 5090]
 [   0    0    0    0 3711 9743 3417 1813]
 [   0    0    0    0 3711 5837 3417   74]
 [   0    0    0 1264  920 4563 3551 7379]
 [   0    0    0 1264  920 4563 3551 1024]
 [   0    0    0 2504 3711 2461 3417 8032]
 [   0    0    0    0 5044 9780 8983 3551]]


In [8]:
## feature representation
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 209ms/step


array([[[ 0.04517311,  0.00121304,  0.01771798,  0.01354397,
         -0.01093245,  0.01016321,  0.00374503,  0.01537231,
         -0.01128148, -0.00445199],
        [ 0.04517311,  0.00121304,  0.01771798,  0.01354397,
         -0.01093245,  0.01016321,  0.00374503,  0.01537231,
         -0.01128148, -0.00445199],
        [ 0.04517311,  0.00121304,  0.01771798,  0.01354397,
         -0.01093245,  0.01016321,  0.00374503,  0.01537231,
         -0.01128148, -0.00445199],
        [ 0.04517311,  0.00121304,  0.01771798,  0.01354397,
         -0.01093245,  0.01016321,  0.00374503,  0.01537231,
         -0.01128148, -0.00445199],
        [ 0.04382085, -0.00586213, -0.04788542,  0.03319087,
         -0.00617975, -0.00758276, -0.04949867, -0.02002232,
         -0.02742655,  0.03921796],
        [ 0.02981147, -0.01477768, -0.04062446,  0.03054902,
         -0.02187817, -0.03818989, -0.04345287, -0.02417095,
          0.01359323,  0.02875931],
        [-0.00625515,  0.02915451,  0.03372246,  0.0

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 3711, 9743, 3417, 5090])

In [14]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 37ms/step


array([[ 0.04517311,  0.00121304,  0.01771798,  0.01354397, -0.01093245,
         0.01016321,  0.00374503,  0.01537231, -0.01128148, -0.00445199],
       [ 0.04517311,  0.00121304,  0.01771798,  0.01354397, -0.01093245,
         0.01016321,  0.00374503,  0.01537231, -0.01128148, -0.00445199],
       [ 0.04517311,  0.00121304,  0.01771798,  0.01354397, -0.01093245,
         0.01016321,  0.00374503,  0.01537231, -0.01128148, -0.00445199],
       [ 0.04517311,  0.00121304,  0.01771798,  0.01354397, -0.01093245,
         0.01016321,  0.00374503,  0.01537231, -0.01128148, -0.00445199],
       [ 0.04382085, -0.00586213, -0.04788542,  0.03319087, -0.00617975,
        -0.00758276, -0.04949867, -0.02002232, -0.02742655,  0.03921796],
       [ 0.02981147, -0.01477768, -0.04062446,  0.03054902, -0.02187817,
        -0.03818989, -0.04345287, -0.02417095,  0.01359323,  0.02875931],
       [-0.00625515,  0.02915451,  0.03372246,  0.00863515, -0.02408912,
        -0.03340074, -0.00561436, -0.03487611