In [16]:
from tensorflow.keras.preprocessing.text import one_hot

In [17]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [18]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [19]:
## Define the vocabulary size
voc_size=10000

In [20]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[498, 9812, 4545, 6879],
 [498, 9812, 4545, 2449],
 [498, 4421, 4545, 5863],
 [5580, 942, 6718, 9383, 5985],
 [5580, 942, 6718, 9383, 1634],
 [4039, 498, 7382, 4545, 5142],
 [4600, 3181, 9648, 9383]]

In [21]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [22]:
import numpy as np

In [23]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  498 9812 4545 6879]
 [   0    0    0    0  498 9812 4545 2449]
 [   0    0    0    0  498 4421 4545 5863]
 [   0    0    0 5580  942 6718 9383 5985]
 [   0    0    0 5580  942 6718 9383 1634]
 [   0    0    0 4039  498 7382 4545 5142]
 [   0    0    0    0 4600 3181 9648 9383]]


In [24]:
## feature representation
dim=10

In [25]:
model=Sequential()
model.add(Embedding(voc_size,dim))
model.compile('adam','mse')

In [26]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [27]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step


array([[[ 0.04440055,  0.00217021,  0.01292335, -0.02686054,
          0.02671142,  0.03286796, -0.04619718,  0.02665149,
          0.03590291,  0.04266173],
        [ 0.04440055,  0.00217021,  0.01292335, -0.02686054,
          0.02671142,  0.03286796, -0.04619718,  0.02665149,
          0.03590291,  0.04266173],
        [ 0.04440055,  0.00217021,  0.01292335, -0.02686054,
          0.02671142,  0.03286796, -0.04619718,  0.02665149,
          0.03590291,  0.04266173],
        [ 0.04440055,  0.00217021,  0.01292335, -0.02686054,
          0.02671142,  0.03286796, -0.04619718,  0.02665149,
          0.03590291,  0.04266173],
        [-0.0003328 , -0.04943242, -0.01261348, -0.02313155,
          0.00335573, -0.02156523, -0.02135499, -0.01746728,
          0.03226231,  0.02085773],
        [ 0.02376716,  0.04685081,  0.00863222,  0.00026296,
          0.04371711, -0.04871918,  0.04122856, -0.03734728,
         -0.02391369,  0.03209991],
        [-0.02237817,  0.01677897, -0.0469715 ,  0.0

In [28]:
embedded_docs[0]

array([   0,    0,    0,    0,  498, 9812, 4545, 6879])

In [29]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None